### ISSUE TITLE
inquiry

### ISSUE THREAD

**Issue by shootcraft** [PYRRH4/SurvivalMysteryChests#1]
### Issue description

I have no idea what it means by chest id ????

### Versions

Spigot : 

PyrCore : 

SurvivalMysteryChest :

**Comment by GuillaumeVDN** [comment]
it's the chest associated key in the configuration.

in this example, the id is "free_chest_id" :  
`chests:
  free_chest_id:
    settings:
      name: "&bFree chest"
      price: "&aFree"
      delay: 120
      size: 54
      choice: 5`
